### ISSUE TITLE
Interested in taking over the hosting (and contributing)

### ISSUE THREAD

**Issue by michaelsmoody** [stt-datacore/website#1]
Kirkman and I have been working on the old iampicard codebase from time to time for additional features and such (again, as an assist tool to help make decisions, not the other concerns). I'm a tech professional, and I would like to take over hosting the tools if you're interested, and of course, contributing. I've been playing since launch day along with a close family member, and we are grateful for these tools.

I'm familiar with pretty much all of the toolchain and dependencies across your tools, and I can easily takeover (having many servers out there that can run the containers and any other necessary services).

Let me know if this is helpful. I'm happy to discuss my tech credentials and experience if you would like.

Thanks,
Michael

**Comment by TemporalAgent7** [comment]
There is a community of people that is currently attempting to self-organize which wants to work towards the same goals. Please reach out on Discord at https://discord.gg/u2raEv .

**Comment by KTDAMN** [comment]
> Kirkman and I have been working on the old iampicard codebase from time to time for additional features and such (again, as an assist tool to help make decisions, not the other concerns). I'm a tech professional, and I would like to take over hosting the tools if you're interested, and of course, contributing. I've been playing since launch day along with a close family member, and we are grateful for these tools.
> 
> I'm familiar with pretty much all of the toolchain and dependencies across your tools, and I can easily takeover (having many servers out there that can run the containers and any other necessary services).
> 
> Let me know if this is helpful. I'm happy to discuss my tech credentials and experience if you would like.
> 
> Thanks,
> Michael

Hi Michael. We'd be really interested in discussing your ideas and work on the the project. If you use discord, join us on the community project at https://discord.gg/uACdRfH. If not let us know an easy way to chat about what we're doing.

Thanks
Kevin
