### ISSUE TITLE
Player Tools issues

### ISSUE THREAD

**Issue by Darxide23** [stt-datacore/website#109]
Importing your player profile throws this error:

>Error
>Failed to read the data. Make sure the page is loaded correctly and you copied the entire contents! (SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data)

However pressing the import data button a second time works just fine. It always gives this error the first time you press it.

The second issue is that the Player Tools tab forgets you if you leave the tab. So if I'm in crew retrieval and I click somebody to look at their stats and then go back to Player Tools, I have to reimport my player data again. it would be nice if it could remember you.

**Comment by ineffyble** [comment]
The new and improved Player Tools remembers you now - let us know how you go!

**Comment by Darxide23** [comment]
Tested it and it works great in Firefox and Chrome! The issue with the error only happens in Firefox and is probably something to do with my own settings, so probably ignore that part.

Your hard work is appreciated!
