### ISSUE TITLE
Disabled menu items

### ISSUE THREAD

**Issue by eitanmk** [stt-datacore/website#11]
There are two items in the top menu that are disabled that I assume these were tools available in the iampicard tool:

- Missions
- Ships

Are we planning to build the functionality for these pages? What content should they provide?
If not, should we just remove the menu items?

**Comment by paulbilnoski** [comment]
In the old tool:
The Missions page showed mission nodes, requirements to complete, which are completed, and which of your crew has the best chance to complete a node.
The Ships page showed owned ships, level, number of schematics (indicating which ships are at max level and have extra schematics you can use for replicator fuel), and other ship details.

**Comment by eitanmk** [comment]
Thanks, @paulbilnoski. It sounds like both might belong under the "player tools" umbrella now, right?

**Comment by TemporalAgent7** [comment]
The Missions entry I just forgot to remove, it's actually Episodes (see https://github.com/stt-datacore/website/issues/7). For the ships, we' have ship_schematics.json in the structured data, just need to build a nice view around that (that lists all ships with their images, names, details and stats, etc.)

**Comment by AlexCPU** [comment]
Looks like these menu items were cleaned up at some point.
