### ISSUE TITLE
Change Accreditation section for Big Book Editors 

### ISSUE THREAD

**Issue by KTDAMN** [stt-datacore/website#132]
We have a request for additional accreditation for the big book page 
Change header text on https://datacore.app/bb
from: 
  "This page collates structured crew stats with insightful details from u/Automaton_2000's Big Book. Content used with his permission, see the original document here."

to:
"This page collates structured crew stats with insightful details from Big Book of Behold Advice, created by Automaton_2000, content used with his permission, see the original document here.
Also contributing: OhMy-StarsAndGarters, [ISA]BigMcLargeHuge, =GBP= Plain Simple Garak, DCPilot, AintEverLucky, Jenos Idanian and Captain Idol"

**Comment by ineffyble** [comment]
Auto has also requested that we add the header text from /bb to /bigbook2 (the image-only one) as well, and that we update the link to https://docs.google.com/spreadsheets/d/1CYR5jnqtacbQM9MIsXp6ATs84Q3rbRM3SmKmUtBvlJ0/edit?usp=sharing
