### ISSUE TITLE
Add some way to clear session storage/force reupload json

### ISSUE THREAD

**Issue by silasary** [stt-datacore/website#133]
I have done some stuff in-game, and want to refresh my data to evaluate changes.  Short of using Browser settings to clear it, there is no visible way to get back to the upload page.

**Comment by AlexCPU** [comment]
![image](https://user-images.githubusercontent.com/4178651/110954797-d3d48d00-8340-11eb-83f2-a71475a60573.png)
Click on the drop down here and select "Update now".
