### ISSUE TITLE
Voyage calculator error

### ISSUE THREAD

**Issue by magicianer** [stt-datacore/website#14]
![Voyage calculator error](https://user-images.githubusercontent.com/25535819/92150095-e8adf200-edec-11ea-94ce-9537630d7aa4.png)

I've tried a few times with the same error each time.

**Comment by emileemilsson** [comment]
I just pasted my json and it works like a charm, can you attach yours ?

**Comment by magicianer** [comment]
After playing the game some more and trying again, it worked. I don't have the json copied that gave the error message. If it happens again, I'll provide it. Thanks @emileemilsson
