### ISSUE TITLE
Voyage Calculator does not consider frozen crew when "

### ISSUE THREAD

**Issue by KeiraenW** [stt-datacore/website#15]

**Comment by KeiraenW** [comment]
When using the Voyage Calculator, results are the same when i select include frozen crew and when I don't select use frozen crew
In both cases it only uses non-frozen crew

When I compare the result with the IAmTosk app, the results are the same when not using "use frozen crew). When including frozen crew however, that app does give 6 unfreeze suggestions.

**Comment by KeiraenW** [comment]
![image](https://user-images.githubusercontent.com/34413657/92299584-c4b8f080-ef53-11ea-89c1-49e3ab406811.png)
![image](https://user-images.githubusercontent.com/34413657/92299586-c97da480-ef53-11ea-91ad-d58d17b6e4aa.png)
![image](https://user-images.githubusercontent.com/34413657/92299587-cc789500-ef53-11ea-9400-9dfcb7b77bde.png)
![image](https://user-images.githubusercontent.com/34413657/92299588-cf738580-ef53-11ea-873c-0fa3b92a5ef2.png)

**Comment by ineffyble** [comment]
@KeiraenW This should be fixed now - let us know if you still encounter any issues.
