### ISSUE TITLE
Discard FF crew in crew retrieval

### ISSUE THREAD

**Issue by mururoa** [stt-datacore/website#155]
Hi,
You may add a default filter for crew retrieval for discarding already FF crew.
Not much reason to retrieve a crew we already own FF no ?
I mean, the whole idea behind crew retrieval is to be able to get crew we don't own or copy of crew we don't have already FF.
So the idea is to have a filter : show unowned crew and crew not FF.

**Comment by ineffyble** [comment]
Hey, I think we need to be careful not to assume specific user behaviour/intent. Some players do run dupes and I'd bet a few might even retrieve them.

So I wouldn't want to change default behaviour.

But I think adding an option for "Not FF (owned or unowned)" makes sense and a few players have requested it. Tracking that at #165.
