### ISSUE TITLE
Transform applied to all images.

### ISSUE THREAD

**Issue by GBora** [stt-datacore/website#163]
There is a css rule that is messing up the images:
```
img {
    transform: rotate(180deg);
}
```
It seems to be inline css so I guess it's not supposed to be in the non-dev version.

**Comment by ineffyble** [comment]
DataCore is experiencing an Acute Peripheral Reflective Inversion Loop which is Fractally Obstructing Ontological Layouts Surprisingly.

It should be back to normal in a day or so.
