### ISSUE TITLE
Fleet information no longer displaying

### ISSUE THREAD

**Issue by vexedfromoz** [stt-datacore/website#192]
![image](https://user-images.githubusercontent.com/79959636/113643340-70324b00-96c5-11eb-88e6-90af83016ab3.png)

I use this page for the fleets I look after for record keeping

**Comment by ineffyble** [comment]
Hey, there's currently a manual process to keep this part of the site running, which means it goes down for a small period once every few weeks. Will fix up in a moment.

**Comment by ineffyble** [comment]
Fixed :) will create an issue around automating that part

**Comment by vexedfromoz** [comment]
thank you :)
