### ISSUE TITLE
Small QoL Suggestion: Quick Clear Button in Crew Stats Search Bar

### ISSUE THREAD

**Issue by tr3kker** [stt-datacore/website#20]
I have no programming experience at all and have no idea how easy/hard this would be, but would it be possible to add a 'Clear' or 'X' button next to the search bar on the Crew Stats window to allow a quick clear of any typed information in the search bar?

Currently, the site keeps the most recent search information in the bar (even after leaving the site and coming back to it later).  While a user can just highlight and delete the existing entry, a button of some sort would allow a 1-click clear and speed up searches a bit. 👍 

Thanks for reviewing my suggestion.

**Comment by AlexCPU** [comment]
Fix should appear within ~1 hour once cache expires

**Comment by tr3kker** [comment]
This is perfect!  Great work! 👍
