### ISSUE TITLE
Crew.csv export has undefined values

### ISSUE THREAD

**Issue by PrydeP** [stt-datacore/website#204]
When exporting the csv file for use in other applications (DNA, CIDAS), there are a bunch of values that come back as undefined.  It seems to be intermittent.
[crew.csv](https://github.com/stt-datacore/website/files/6307019/crew.csv)

**Comment by ussjohnjay** [comment]
@PrydeP I believe this should be fixed now, thanks to some changes in #201. Please let us know if you are still running into this problem.

**Comment by AlexCPU** [comment]
Fixed in #201
