### ISSUE TITLE
Bug: Incomplete Ships being shown under unneeded items

### ISSUE THREAD

**Issue by badrobit** [stt-datacore/website#21]
If I go to my [unneeded items (link to shared profile)](https://datacore.app/profile/?dbid=520533334650880), it always lists captain pikes enterprise as an unneeded item.  

![image](https://user-images.githubusercontent.com/1327963/94999126-38671100-0585-11eb-9bd6-e2d3ccdeb7ee.png)

I like that it lists which schematics I need but I never get ships that are actually completed. Just to be sure, here is the current state of my Pike's Enterprise (schematics clearly still needed):

![image](https://user-images.githubusercontent.com/1327963/94999141-651b2880-0585-11eb-9974-9ca541bc7ba2.png)

**Comment by ineffyble** [comment]
@badrobit This should be fixed now - let us know if you still encounter any issues.

**Comment by badrobit** [comment]
> @badrobit This should be fixed now - let us know if you still encounter any issues.

Just confirming that I am seeing it as fixed, awesome job!
