### ISSUE TITLE
Size differences between colour themes

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/website#213]
There's some sort of size or padding difference on the menu between the light and dark themes.  Most easily noticeable when toggling between the themes as the theme button jumps around.

**Comment by AlexCPU** [comment]
Actually looking further, it's far more significant than just the menu size, if you swap between themes on a crew page, you can see literally everything is different sizes.

**Comment by theglette** [comment]
I have fixed the size differences in the theme css files and have submitted a pull request for this issue. #240
