### ISSUE TITLE
(display?) issue when tanking shuttles

### ISSUE THREAD

**Issue by NuvuCika** [stt-datacore/website#227]
Hi,

when tanking shuttles, I noticed a display of "0 hours", when there are still several shuttles to tank. 
I first noticed it when tanking Augments. When I mentioned it on discord, ChukwuOsiris asked me to report it here, if I saw it again. So when tanking Section 31, I kept an eye out and here it is again:

![Screenshot (301)](https://user-images.githubusercontent.com/84469724/118860019-2f8c3b00-b8db-11eb-83e9-32d7049f032a.png)

(I was also asked to share my player.json, but I don't really know how? If needed, please direct me.)

In closing, ab big thank you to all of you who put so much dedication, effort and time into this site!

Regards

Nuvu Cika

**Comment by NuvuCika** [comment]
[I hope that is the information needed.txt](https://github.com/stt-datacore/website/files/6511129/I.hope.that.is.the.information.needed.txt)

**Comment by joshurtree** [comment]
Thanks for the info. Setup a pull request to fix it
