### ISSUE TITLE
Privacy leak starting from fleet leaderboard.

### ISSUE THREAD

**Issue by FUNimations** [stt-datacore/website#261]
I saw people on facebook complaining about the fleet leaderboard, and it could lead to poaching.
In itself i don't see the issue with a fleet leaderboard. Except that if anyone ever used the player tool. ANYONE can see that profile now.
This could lead to poaching but is a privacy concern as well.
It leaves out information about who is paying to win in this game, and what crew they have to compete in events.
That's unacceptable.

If anyone uses the player tool, at least generate some accesstoken cookie linked to the player profile, and prevent unauthorized access, this token can be used in url's to the profile as welll, in case anyone want's to share their profile. But the token should always be allowed to be invalided when uploading your player data again.

**Comment by ineffyble** [comment]
Thank you for your feedback on our Event Information feature. This feature is still under active development and not officially released, and we will consider your views when further development work is undertaken.

Thank you also for raising concerns regarding player privacy. Privacy and security are key concerns that the DataCore development team consider as part of all our work.

With regards to the specific privacy concerns you have raised, please note the following:

* Only players who explicitly opt in to sharing their profile via DataCore will have their profile visible on the DataCore website.
* Using DataCore Player Tools does not automatically share a player's profile, and many people can and do use Player Tools without choosing to share.
* Players who opt-in are informed ahead of time that the data will be publicly visible.
* Player profiles contain no personally identifiable information about the individual, only information about their in-game account, much of which is already available directly in-game.
* Player profiles visible on the DataCore site are only accurate at the time of sharing. If someone shared their info once a year ago, the information visible is a year old.

If any person wishes to share their player data with others without making it publicly visible, they are encouraged to use the "Export crew spreadsheet" feature, which will provide them with a spreadsheet without sharing their profile.

If any person who has previously shared their profile using DataCore Player Tools no longer wants their profile to be visible, we will be happy to remove it if they reach out (via email to admin@datacore.app or via [our Discord](https://discord.gg/2SY8W7Aeme)

I hope that helps clear things up. Let us know if you have further concerns.

**Comment by FUNimations** [comment]
When i used the tool out of curiousity a good year ago, i seem to remember something saying that the data would be available to anyone who had your dbid. Nothing about an optin.
But it's a whole other thing sharing your dbid with someone and having a site where you can just look it up.

![image](https://user-images.githubusercontent.com/16779422/127767271-f91d1fcc-3876-4cc2-bded-26cfe2f86e46.png)
Feel free to use my screenshot and highlight where the optin is asked, but i'm not seeing it.
Might be it happens after you upload, but honestly, i'm not going to take your word and try uploading my profile just to see if there indeed is an optin (now).
And after the optin is the person really informed about what is shared?
Because you can see vip levels; This gives people an idea about the financial situation of a player, and could lead to in game chat scamming of poaching. Are people really aware of that fact when they optin?

**Comment by ineffyble** [comment]
> But it's a whole other thing sharing your dbid with someone and having a site where you can just look it up.

The current disclaimer states that your profile will be *publicly accessible* and mentions the scenarios of someone knowing your DBID or having a link to the profile. DataCore does not offer any ability to look up particular players directly. However, player profiles are shown on associated entities (e.g. Fleet Information pages and the not-yet-released Event Information pages, if the player appears on an event leaderboard). You are correct that this disclaimer could be more explicit with regards to the new functionality, and as part of releasing the Event Information feature I'll make sure we add that to the list of scenarios.

> Feel free to use my screenshot and highlight where the optin is asked, but i'm not seeing it.

When you paste your data into the box and click "import data", no data is uploaded to DataCore. Player Tools runs entirely locally. If you were to do that, on the next screen you would see an option to "Share your player profile", which is where users have the choice to upload their data.

> after the optin is the person really informed about what is shared?

That button has a disclaimer that your profile will be visible, and mentions some of the data that will be available: **"captain name, level, vip level, fleet name and role, achievements, completed missions, your crew, items and ships"**. Additionally, after you click the "share your profile" button, you are taken to your shared profile, and can see everything that is there.

> Are people really aware of that fact when they optin?

Yes, assuming they read the text next to the button, which makes it abundantly clear that VIP level is included in the profile.

**Comment by AlexCPU** [comment]
I'm going to close this, as there's nothing to fix here.
