### ISSUE TITLE
Add Voyager and Gauntlet Ranking

### ISSUE THREAD

**Issue by NormalDesmond** [stt-datacore/website#27]
I understand the information is already available in each character's individual screen, but it would be helpful to be able to pull a list of top voyagers or gauntlet ranks. Perhaps adding sortable columns to the Crew Stats page for Voyage Rank and Gauntlet Rank (and maybe even Events?) would be a simple solution?

**Comment by ussjohnjay** [comment]
A sortable column for voyage rank and a sortable pseudo-column for event count were added earlier this year. The crew stats page can now also sort by gauntlet rank when clicking the gauntlet rank from an individual crew page.
