### ISSUE TITLE
Searching by trait is matching names as well

### ISSUE THREAD

**Issue by Darxide23** [stt-datacore/website#271]
For example, searching for `trait:kai` will still bring up Buck Bokai as a result. Unless there's been a serious reformation within the Bajoran religion that I'm unaware of, this is of course an error.

**Comment by ussjohnjay** [comment]
Most crew have a trait that helps identify their variant. In this case, the term `buck_bokai` is the variant trait of Buck Bokai, and it's the thing getting matched by your search for `trait:kai`. This likely happens with a few other variant traits too.

At some point we'll add better ways to do advanced searches that will reduce false positives like this, but for now, let's assume that the Emissary has converted Bajor into a big baseball fan club.

**Comment by Darxide23** [comment]
> let's assume that the Emissary has converted Bajor into a big baseball fan club.

This is now canon and there's nothing you can say to convince me otherwise.

I also tried with double quotes around `kai` and it still didn't help. I think double quotes should be searched for as a complete string and not a substring. I believe this may have been requested in the past.

**Comment by ineffyble** [comment]
@Darxide23 click "Match any text" and try the other options. Should do what you want.

**Comment by Darxide23** [comment]
This whole time and I never knew that was a drop down!
