### ISSUE TITLE
[Bug] Mismatch between CAB info reported by DataCore and the CAB website for some crew

### ISSUE THREAD

**Issue by netWilk** [stt-datacore/website#274]
There seems to be a mismatch between CAB rating reported by DataCore site and the source CAB sites for some of the crew.

Issue exists at least for Archaeologist Q.

![image](https://user-images.githubusercontent.com/89749923/131264859-3b8b548b-1a82-4b14-84f5-14fff546dada.png)

![image](https://user-images.githubusercontent.com/89749923/131264902-170e4ccd-11ba-41a2-90c1-11a2141dafe8.png)

**Comment by ineffyble** [comment]
@netWilk This is because Archaeologist Q's power rating was bugged until recently. Travelling Man fixed it a day ago but DataCore hasn't synced CAB ratings since then: https://forum.disruptorbeam.com/stt/discussion/comment/249595/#Comment_249595

Will run the sync now.

**Comment by AlexCPU** [comment]
Closing as resolved by latest sync.
