### ISSUE TITLE
Feature: Add option to dismiss announcement messages

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/website#299]
I'd probably implement this by storing the date that we dismissed, such that any new announcements after that still show up.

Happy to have a debate as to if this is even needed with announcements only staying for 3 days.

**Comment by ussjohnjay** [comment]
Thanks for merging the PR so quickly. That little announcement will save me from getting a bunch of confused DMs from my fleetmates. :)

I was thinking we could bump the expiration up to 7 days if the announcement is dismissible. And storing the date makes perfect sense, assuming we're only showing the most recent announcement.
