### ISSUE TITLE
Equipment images don't load when first swapping to "Crew (mobile)" tab

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/website#3]
Reproduction steps:
1. Use Chrome, open developer console
2. Goto [https://datacore.app/voyage](https://datacore.app/voyage) and paste the player.json into the box
3. Click Read Data
4. Switch to Crew (mobile) tab
5. Observe a crew member that has items equipped, these will show a broken image.  Developer console will show a 404 error for https://assets.datacore.app/undefined which has been attempted to be loaded for each equipment image.
6. Swap back to the voyage calculator tab
7. Swap back to Crew (mobile) tab
8. Observe that the equipped items now load correctly

Has also been reproduced locally on development version

**Comment by AlexCPU** [comment]
At step 5:
![before](https://user-images.githubusercontent.com/4178651/87228560-ef465d00-c399-11ea-9840-6121b43deb5d.png)

At step 8:
![after](https://user-images.githubusercontent.com/4178651/87228564-f2414d80-c399-11ea-8f96-48caabb44d4f.png)

**Comment by AdmiralMemo** [comment]
I've been having this issue for a while, so thanks for letting me know that the switch and switch back fixes it as a workaround, at least. :-)

**Comment by ineffyble** [comment]
Confirming this is still an issue.

**Comment by AlexCPU** [comment]
Fixed by #201
