### ISSUE TITLE
Feature : What if I had

### ISSUE THREAD

**Issue by mururoa** [stt-datacore/website#350]
How about to add a functionality like "what if I had" that is on the Captain Idol Datacore Analysis sheet ?
A way to see what benefits a crew could provides.
For example to see if next event legendary worth the efforts we have to do to get him or not at all or to decide on crew beholds.
Or to see if that event super rare would contribute to event efforts in event planner or not.

**Comment by ussjohnjay** [comment]
A "preview on your roster" button was added to crew pages and the behold tool in #355 to let you view prospective crew alongside your existing roster, allowing you to compare skills in the crew player tool. You can also add prospective crew manually in this tool (and the event planner).
