### ISSUE TITLE
100% Voyage Chance Not Correct

### ISSUE THREAD

**Issue by AdmiralMemo** [stt-datacore/website#351]
The image should speak for itself, but the calculator claims that this should have a 100% chance on a 10-hour voyage, while every other calculation and the graph implies differently.
![100PercentChance](https://user-images.githubusercontent.com/9385889/158285862-87c63563-b8f9-4884-ae5e-78ec8dab0e93.png)

**Comment by ussjohnjay** [comment]
This should be fixed now with #377.
