### ISSUE TITLE
Player Tools → Crew: Add filter to eliminate max-star and immortalized crew

### ISSUE THREAD

**Issue by ylluminate** [stt-datacore/website#359]
I find that it would be useful to be able to consider the Crew tool without maxed / immortalized crew. I frequently find myself asking "what crew should I work on next that I already have?" I end up having to really work hard with so many immortalized crew to find good targets that line up well with my goals.

**Comment by ussjohnjay** [comment]
Options for roster maintenance, including filtering out immortalized crew, was added to the crew player tool in #394.

**Comment by ylluminate** [comment]
That's awesome @ussjohnjay! Can you also add a filter for level ranges? In other words "< 100" or something that allows us to filter out certain level ranges? Or maybe simply "not 100" would be sufficient. I have always wondered why there wasn't a columnar sort for level as well...

**Comment by ussjohnjay** [comment]
@ylluminate I'll have to think about an efficient way to filter by level. In the meantime, I'll add a level "pseudocolumn," so that if you click the "crew" column header, one of the toggles will let you sort by crew level.

**Comment by ylluminate** [comment]
Appreciate it @ussjohnjay. This new Boss Battle situation seems to make this perhaps more pertinent now in some regards.

**Comment by ylluminate** [comment]
So @ussjohnjay another problem our fleet is seeing is that we need a better way to ascertain which crew meet the "combo chain" for each boss battle. In this case we need a way to do MUTUAL ("and") operations. For example, on Normal Combo Chain right now we see that we need:
* Human + ? (we found Vulcan was (the/an)other)
* Betazoid + ? (we found Diplomat was (the/an)other)
* Communicator + ?
* Desperate + ? + ?

So as you can see, we need to be able to filter by traits such that we can have multiple (sadly at least more than two we're seeing) trait matching to determine best crew permutations to try with various fleet members...

**Comment by ussjohnjay** [comment]
@ylluminate We're still collecting data on fleet boss battles, which will hopefully point us in the right direction as to the tool we should build on DataCore.

In the meantime, this is what I suggest for matching traits. In your example, type `trait:communicator` into the search box of the crew player tool. Then select all remaining possible combo traits in the trait filter dropdown. This will find any of your crew that match communicator and any one of the traits you selected.

Again, we're still considering ways to streamline this, but the method above ought to be functional enough for these early days.

**Comment by ylluminate** [comment]
When using "Ship Abilities" the search field does not trigger searching on traits such as "hulls" for looking for hull repair on existing crew. Is this expected or a bug?

**Comment by ylluminate** [comment]
Also, the more and more I use DataCore, the more I realize that we need level sorting. For example, in collections it's often useful to see the level in order of your highest to lowest for - for example - on 4* in order to know which ones are closest to fulfilling a collection. In other words, it's just a lowest hanging fruit / less work determination since sometimes (for me) it I prefer to knock how higher leveled crew since it may end up being a little less work (I guess for a middle-aged crew roster).

**Comment by ussjohnjay** [comment]
You can use the `ship:` prefix to do some (very primitive) searching of ship abilities, e.g. `ship:hull` for hull repair or even `ship:repairs` for any type of repair ability.

I'll be sure to add sorting by level to other tables that need it, when the other tools are next updated.
