### ISSUE TITLE
Feature request: Simple counter of Immortalized/Duplicated/Frozen crew

### ISSUE THREAD

**Issue by venimus** [stt-datacore/website#381]
People often brag/celebrate of how many crew they have, but they don't really know that, because in fact there is no simple way to get the real number of how many crew we immortalized. The in-game counter in Cryostasis Vault is buggy and does not show the actual immortalized crew especially when there are dupes. You can do a simple check by freeze/unfreeze crew and watch the counter. The achievement counter (which disappear after 600) is buggy and unreliable too.
It would be really nice to have a proper simple counter of how many crew is immortalized (w/ or w/o dupes).
There is so many number in stats page, but nowhere the immortalized count can be found.
I guess also a chart similar to "Owned vs. Not Owned crew per rarity" would fine too.

**Comment by ussjohnjay** [comment]
A roster summary button has been added to the bottom of the crew player tool, which inventories your crew by rarity, skills, immortalizations, among other things.
