### ISSUE TITLE
When trying to paste "Export to CIVAS" from clipboard into the CIVAS sheet, data is in the wrong orientation

### ISSUE THREAD

**Issue by jdarcy2012** [stt-datacore/website#389]
1. Load data on Datacore that has a recalling voyage.
2. Go to Voyage.  Click Export to CIVAS.
3. Open your CIVAS sheet.  Locate the correct Primary / Secondary pair and find go to an empty column.
4. Paste.

The data comes out horizontally.

Note: I have tried pasting transposed but nothing happens.

Environment: Chrome for Windows 102 and 103, Chrome for Android, latest version.  Also tested by obtaining clipboard data from Edge (Chrome) 103.

**Comment by ussjohnjay** [comment]
CIVAS recently got a big update, see here: https://docs.google.com/spreadsheets/d/1edSWAoaqFMK4S9CSI7Qk21iNSWKExZGeySp06CW1B4c/edit?usp=sharing

DataCore's voyage calculator has been updated to be more compatible with the (horizontal) format of the new version.

**Comment by jdarcy2012** [comment]
Guess I better look at the new version.  Hadn't caught up with it, yet.  Just realized it even existed about 2 days ago.  Thanks!
