### ISSUE TITLE
Bug: Searching for traits that are substrings of other traits is impossible

### ISSUE THREAD

**Issue by ineffyble** [stt-datacore/website#39]
The most extreme case of this is `trait:q` which shows every crew with a trait that begins with the letter Q, and as far as I can tell, there's no way to just see all the Q.

Should probably make the `trait:` filter only match on whole word (although not sure how it handles spaces in trait names currently?)

**Comment by Darxide23** [comment]
When it comes to members of the continuum, they all have the trait "Q Continuum" which you can search. But your point is still valid. I'd suggest that putting a search term in quotes mean an exclusive search without searching substrings.

**Comment by ineffyble** [comment]
@Darxide23 but if I just want to see variants of the character Q, no such luck. Another example is `trait:tas` shows the character `Tash`.

**Comment by Darxide23** [comment]
The John deLance character Q can be searched for with the trait `q_jdl`

**Comment by ineffyble** [comment]
This was fixed in #78 although better documentation is needed as per #101.
