### ISSUE TITLE
FBB tool not displaying all eligible crew

### ISSUE THREAD

**Issue by enigmaticgrace** [stt-datacore/website#417]
Hi all,

The FBB tool is fantastic, but I've twice noticed it not displaying all eligible crew. The first time, the missing crew matched a trait that had been listed twice, with one instance greyed out (but the other still available).

The second one, I took screenshots of. The tool shows only one crew that fits the remaining node; however, there are two. (Mok'bara Worf matches spiritual/Klingon). The "possible traits" selection displays correctly, but Worf doesn't show up in the list.

![image](https://user-images.githubusercontent.com/114256277/192043067-e5903820-3243-4966-b4d5-628dbd33cf43.png)
![image](https://user-images.githubusercontent.com/114256277/192043137-e84ec88d-3c07-4fc0-bd7d-42ea27ea41dc.png)
![image](https://user-images.githubusercontent.com/114256277/192043269-e9eddea6-2ddc-465f-a7c1-cdcba2b66b52.png)

Hoping this will help someone figure out the reason for the glitch. Good luck, and thanks!

**Comment by ussjohnjay** [comment]
The tool seems to be operating as expected here. Mok'bara Worf can't be a solution for this node. He's a non-portal crew, so neither his spiritual trait nor his Klingon trait is considered viable (because no other possible crew for that node has those traits).

**Comment by enigmaticgrace** [comment]
Ah, I’d forgotten he wasn’t portal yet. That explains it - thanks!

**Comment by ussjohnjay** [comment]
No problem. If you encounter anything else that you think isn't right, just let us know. Always appreciate the feedback!
