### ISSUE TITLE
Pike's USS Enterprise Schematics shows up under Items, not Schematics

### ISSUE THREAD

**Issue by AdmiralMemo** [stt-datacore/website#46]
Title says it all. When looking through the "Unneeded Items" tab, these Schematics show up in the wrong spot.
![image](https://user-images.githubusercontent.com/9385889/106644619-4c357a80-6559-11eb-8886-604bc0e92575.png)

**Comment by ineffyble** [comment]
@AdmiralMemo Do they also show under the schematic section? Also, I'm assuming that you have the ship max level?

**Comment by ineffyble** [comment]
@AdmiralMemo This should be fixed now - let us know if you still encounter any issues.
