### ISSUE TITLE
Issues with Short Names in Export

### ISSUE THREAD

**Issue by AdmiralMemo** [stt-datacore/website#477]
The Short Name of "Amanda" in the Export is listed for Amanda Rogers, Amanda Cole, Amanda Grayson, and Awaiting Amanda Grayson, while Graduation Amanda Grayson has a Short Name of "Amanda Grayson" instead. We've got 3 people sharing a name, and then one variant of one of those people has a different name. Can we get this sorted so all the Amandas aren't lumped as the same person?

**Comment by nmoschkin** [comment]
Sure. Thanks for pointing that out. Will address it either in a spike or in the next release.

**Comment by AdmiralMemo** [comment]
Was wondering if there was an update on this, because it's still the same way.

**Comment by AdmiralMemo** [comment]
I've also found, in descending order of what I consider should be fixed to things that could be preferences:

Tallinn has a typo on the Short Name of Tallin.
Thalen is listed under Kelby for unknown reasons, as they are not remotely the same character.
Brain Drain Crusher and Riker should be listed as Crusher and Riker. (Consistent with Seska and Culluh, for example.)
Barry Waddle is a an alias of Arne Darvin, and I think he should be listed under Darvin.
Friar Tuck Data is a character Data played, and I think he should be listed under Data. (Consistent with Alan-A-Dale, for example.)
Kodrak is a an alias of Odo, and I think he should be listed under Odo. (Consistent with Jodmos, for example.)
Captain Killy is a variant of Tilly, and I think she should be listed under Tilly.
Falcon O'Brien is a variant of O'Brien, and I think he should be listed under O'Brien. (Consistent with Hippocrates Noah, for example.)
Duchamps is a variant of Worf, and I think he should be listed under Worf. (Consistent with Hippocrates Noah, for example.)
Anastasia Komananov is a variant of Kira, and I think she should be listed under Kira. (Consistent with Hippocrates Noah, for example.)
Benny Russell and Night Writing Benny Russel are variants of Sisko, and I think they should be listed under Sisko. (Consistent with Julius Eaton, for example.)
Vindicta Mariner is listed under Vindicta when she's a variant of Mariner.
Beowulf EMH is listed under EMH instead of Doctor where the rest are listed.
Warship EMA is listed under EMA instead of Doctor. (Consistent with Warship Janeway, for example.)
Festive Lwaxana Troi, Grateful Lwaxana Troi, Fascination Lwaxana Troi, and Ambassador Troi are filed under Troi, instead of being a separate character. (Probably just named Lwaxana?)
Angel Gabrielle Burnham, Displaced Gabrielle Burnham, and Qowat Milat G. Burnham are filed under Burnham, instead of being a separate character. (Probably just named Gabrielle?)
Mike Burnham Sr. is filed under Burnham, instead of being a separate character. (Maybe named Mike? Or perhaps Burnham Sr.?)
Lt. Commander Jack Crusher and Rogue Jack Crusher are two separate characters (Bev's husband and son, respectively), both listed under Jack.
Miss Q and Belle Q are listed under Q with the JDL Q character, as is Q Junior, when they're 3 different characters in the same family.
Una and Number One are the same character. I think they should have the same Short Name. (Either would be fine with me.)
Wyatt Earp and Helmsman Wyatt are both listed under Wyatt despite being separate characters.
Lt. JG Sam Lavelle is a separate character from the two Sam Kirks we have, but both are listed under Sam.
Torchbearer Voq is treated by the game as a Tyler, but I can understand if people want them separate.
Colonel Worf is a separate character from our usual Worf, but I don't know if the game treats them the same or not.
Lt. Thomas Riker is a separate character from our usual Riker, but I don't know if the game treats them the same or not.
Xindi-Aquatic Councilor is listed as Xindi-Aquatic, but Xindi Insectoid Councilor is just listed as Insectoid. I was thinking standardize these one way or the other?

**Comment by ussjohnjay** [comment]
Just to chime in here, the short name is determined by the in-game developers, not by DataCore. The most obvious place where you see short names instead of a crew's full name is on the behold screen. Short names are also used to streamline some in-game dialogue and narratives.

As you note, short names are very inconsistent and occasionally misleading. I would not suggest using the short name field for any real purpose. For what it's worth, DataCore determines variants from the crew's hidden traits, which would properly group, for example, all the different Amandas. I don't believe the variant field is in the export, but that might be something worth looking into in the future.

**Comment by AdmiralMemo** [comment]
I discussed this with the folks on the Discord, and they told me basically the same thing. It's frustrating to me that these are bugs from the game's side, and understandable that there's not much y'all can do about it. Keep up the good work.
