### ISSUE TITLE
In Portal issues

### ISSUE THREAD

**Issue by Pumbaa672** [stt-datacore/website#486]
Not sure if it goes here.

When I pull the data and post it to the website, all the true or false for in portal is false except 2 in pic of the crew page from your website.

![image](https://github.com/stt-datacore/website/assets/75749807/5323d4c1-bcdd-4dd1-a2e0-e672c9e4597f)

And from the player data (in excel sorted to portal true)

![image](https://github.com/stt-datacore/website/assets/75749807/5b0d26f3-efdd-4751-979b-f003314cc245)

**Comment by nmoschkin** [comment]
This is known and has been dealt with. A fix was deployed about 10 minutes ago. Please clear your cache and refresh your browser.

**Comment by Pumbaa672** [comment]
Sorry.  Didn't see anything that indicted that you guys/gals was aware of the issue.

**Comment by nmoschkin** [comment]
https://discord.gg/9stgQyH3

**Comment by nmoschkin** [comment]
We mostly communicate through the STT discord server.
