### ISSUE TITLE
Crew Retrieval: view of combinations causes data to be out of position/off screen

### ISSUE THREAD

**Issue by flash82** [stt-datacore/website#61]
The current implementation of the accordion effect to display polestar combinations causes a lot of unintended manual scrolling requirements, because the information you wanted to see is suddenly out of position.

For example: I've looked at the list of combinations for my VA Janeway (25+) and when I clicked to view the details for the next crew directly listed below with only 5 combinations to their name, I needed to scroll up two pages to get to what I wanted to see.

Should we implement an automatic scroll to the top of the accordion effect when it is opened?

**Comment by ineffyble** [comment]
Alternative would be swapping from accordion to modal, may be worth playing with both and seeing what works best.
