### ISSUE TITLE
[Request] Polestar lookup idea

### ISSUE THREAD

**Issue by Darxide23** [stt-datacore/website#66]
It would be helpful if I could pick a polestar that I have (really, just a trait) and have it list out all crew who use that polestar broken down by their Big Book tier rank. I know the tier rank isn't the end all, be all of who is the best crew, but it can definitely point you in the right direction. Bonus points if I can filter the list by card rarity or a secondary trait or skill.

I find that doing this kind of bottom-up search for a crew is a much more realistic approach to finding somebody worthwhile to retrieve rather than doing a top-down search starting from a crew and hoping you have the polestars. The idea of "waiting" for a specific polestar to popup is somewhat of a dream with the vast number of them that are available, so saving polestars to get exactly the one crew I want is not feasible if you think of things in terms of Quantum being the limiting factor. You never want to have capped Quantum, so you'd want to spend it when it was capped (or near capped) which makes the idea of saving polestars sort of unpalatable and therefore a bottom-up search is the most efficient way to manage Quantum. At least, in my opinion.

**Comment by ineffyble** [comment]
@Darxide23 Have you looked at the new "Crew Retrieval" tab in Player Tools?

**Comment by Darxide23** [comment]
Unless I'm missing some functionality, that's the top-down method that I mentioned and not the bottom-up method of searching.

**Comment by ineffyble** [comment]
The tool looks at all the polestars that you personally own, and tells you all the crew you can retrieve with them. That's bottom-up, right?

**Comment by Darxide23** [comment]
I suppose it is. I've looked over it. I guess it actually does work for my purposes. Retroactive thanks!
