### ISSUE TITLE
Crew search examples are not mobile friendly

### ISSUE THREAD

**Issue by flash82** [stt-datacore/website#76]
The main page (crew search) has a list of example search filters, which is shown on a mouse hover on desktop. None of this is user friendly on mobile devices.

In portrait mode the question mark is not displayed at all:

![Screenshot_2021-02-20-09-12-39-145_com android chrome](https://user-images.githubusercontent.com/65423314/108588987-6befdf80-735c-11eb-8841-66e163fee2b3.jpg)

In landscape mode one can see the question mark and tapping on it makes the information stick around, but most of it lies outside of the screen and can't be scrolled to:

![Screenshot_2021-02-20-09-13-08-709_com android chrome](https://user-images.githubusercontent.com/65423314/108589017-904bbc00-735c-11eb-9bd7-ab0131ef35c8.jpg)

Would it break the flow to add a button which opens a modal with the information?

**Comment by ineffyble** [comment]
I think modal is the right call here - although you may want to go with tooltip for desktop/large width devices, and modal for mobile/small width devices.

**Comment by ineffyble** [comment]
Also modal formatting is kind of miserable by default, I am not at all happy with the one I made on the player tools upload page. So you may need to spend a bit of time tweaking.
