### ISSUE TITLE
Pseudocolumn sort order issue and inconsistency

### ISSUE THREAD

**Issue by flash82** [stt-datacore/website#99]
I noticed the problem while using my default browser Firefox. The applied crew search filter was `in_portal:true rarity:4,5 trait:spiritual` and my pagination was 100 crew per page, I've sorted by the big book tier in ascending order. This resulted in T'Kuvma being mis-sorted.

To fix this I've restarted the browser and ultimately tried a new profile, but the sort order shown in the screenshot below persists. Highlighted is the one crew which is mis-sorted:

![Screenshot_2021-02-24 DataCore Firefox](https://user-images.githubusercontent.com/65423314/109016829-da170800-76b6-11eb-8842-ea68b879fab0.png)

Next I looked at the same page using identical filter and sort settings as described above in Chrome (I used the Vivaldi fork due to the integrated full page screenshot tool). While T'Kuvma is sorted correctly, two other crew - Young T'Pau and Vedek Bareil Antos - were mis-sorted instead:

![2021-02-24 15 35 22 datacore app 7fe4951103ee](https://user-images.githubusercontent.com/65423314/109017047-1480a500-76b7-11eb-874a-eee9d4e6cfd3.png)

**Comment by ineffyble** [comment]
Fixed in #135.
